### ISSUE TITLE
请问cut()函数最终执行的dp()函数究竟返回的是什么？good_cut以及矩阵F，u代表什么含义？分词结果如何得到？

### ISSUE THREAD

**Issue by Nickname1230** [GanjinZero/GTS#1]

**Comment by GanjinZero** [comment]
dp函数返回的是分割结果
good_cut代表句子的可行分词数
F[i][j]代表分到第i个字，分j个词的代价函数：代价函数的具体定义见论文
u[i][j]代表分到第i个字，分j个词，第j个词的起始位置
