### ISSUE TITLE
请问数据集具体用的是哪一个呢？

### ISSUE THREAD

**Issue by RingoTC** [GanjinZero/GTS#2]
CCKS2019没有术语发现任务，请问是用NER的数据集做的吗？

**Comment by GanjinZero** [comment]
是的，用的是ccks2019的医学ner任务作为数据集。分词和术语发现的标注都是基于此的。

**Comment by RingoTC** [comment]
就分词而言，ner的数据集没有提供分词的result，请问是如何进行评估的呀？

**Comment by GanjinZero** [comment]
找医学生标注的

**Comment by RingoTC** [comment]
好的 谢谢！
